// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by:
//        'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator'
//
//    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace GdkSample_SignIn
{
public static class GdkPlatformSettings
{
    public static string gameConfigTitleId = "604B6C98";
    public static string gameConfigScid = "00000000-0000-0000-0000-0000604b6c98";
    [Obsolete("gameConfigSandbox will be removed in future releases. Please do not use.", false)]
    public static string gameConfigSandbox = "";
}
}
